config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get "suburbmap", to: 'pages#suburbmap'
  get "latlong", to: "suburbs#latlong"

  resources :organisations
  resources :suburbs
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  belongs_to :suburb

  scope :with_abn, -> { where.not(abn: nil) }
  scope :suburb_count, -> { joins(:suburb).group("suburbs.name").order("count_suburb_id desc").limit(16).count("suburb_id") }

  def full_address
    suburb ?  "#{address}, #{suburb.name}, #{suburb.state}, #{suburb.postcode}" : "#{address}"
  end

  def full_address_html
    suburb ?  "#{address}, <br/> #{suburb.name}, <br/> #{suburb.state}, #{suburb.postcode}" : "#{address}"
  end
end

app/models/suburb.rb
class Suburb < ActiveRecord::Base
  has_many :organisations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [ :show, :edit, :update, :destroy ]

  def index
    @organisations = Organisation.page(params[:page])
  end

  def show
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params);
    @organisation.save
  end

  def edit
  end

  def update
    @organisation.update(organisation_params);
    redirect_to organisations_path
  end

  def destroy
  end
  
  private
  def set_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name, :address, :state, :suburb, :postcode, :website, :lat, :long)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    #@datasets = Organisation.select(:dataset).map(&:dataset).uniq.sort
    @datasets = Organisation.where(dataset: "sacom/adel-and-north").select(:dataset).map(&:dataset).uniq

    if params.has_key?(:datasets)
      @organisations = Organisation.where(dataset: params[:datasets]).includes(:suburb)
    else
      #@organisations = Organisation.all.includes(:suburb)
      @organisations = Organisation.where(dataset: "sacom/adel-and-north").includes(:suburb)
    end

    @organisations = @organisations.with_abn if params[:abn]

    case params[:group_by]
    when "suburbs"
      @org_hash = @organisations.select { |org| org.suburb }.map { |org |
        { lat: org.lat, lng: org.long, infowindow: "#{org.name} <br/> #{org.full_address_html}" }
      }
    else #lat/long
      @org_hash = @organisations.select { |org| org.lat and org.long }.map { |org |
        { lat: org.lat, lng: org.long, infowindow: "#{org.name} <br/> #{org.full_address_html}" }
      }
    end

    @org_suburb_count = @organisations.suburb_count
  end

  def suburbmap
    @suburbs = Suburb.all
    @suburb_hash = @suburbs.select { |suburb| suburb.lat and suburb.long }.map { |suburb|
      { lat: suburb.lat, lng: suburb.long, infowindow: suburb.name }
    }
    @org_suburb_count = Organisation.suburb_count
  end
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  def index
    @suburbs = Suburb.page(params[:page])
  end

  def show

  end

  def new
    @suburb = Suburb.new
  end

  def create
    @suburb = Suburb.new(suburb_params)
    @suburb.save
    respond_to do |format|
      format.html { redirect_to @suburb }
    end
  end

  def latlong
    name = params[:suburb].gsub("suburb_", "").gsub("_", " ")
    @suburb = Suburb.find_by_name(name)

    respond_to do |format|
      format.json
      format.html
    end
  end

  private
  def suburb_params
    params.require(:suburb).permit(:name, :postcode, :state, :lat, :long)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The not-for-profit map" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">The Not-For-Profit Map</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Organisation map", root_path  %></li>
            <li><%= link_to "Suburb map", suburbmap_path  %></li>
            <% if false %>
              <li><%= link_to "Organisation list", organisations_path  %></li>
              <li><%= link_to "Suburb list", suburbs_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>&copy; <a href="http://mateos.cc">Daniel Mateos 2015</a>, For <a href="http://www.connectingup.org">Connecting Up (love)</a></p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_for @organisation, :html => { :class => "form-horizontal organisation" } do |f| %>

    <% if @organisation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @organisation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:address]) %>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:website]) %>
  </div>
  <div class="control-group">
    <%= f.label :dataset, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dataset, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:dataset]) %>
  </div>
  <div class="control-group">
    <%= f.label :lat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:lat]) %>
  </div>
  <div class="control-group">
    <%= f.label :long, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :long, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:long]) %>
  </div>
  <div class="control-group">
    <%= f.label :suburb_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :suburb_id, :class => 'form-control' %>
    </div>
    <%= error_span(@organisation[:suburb_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            organisations_path, :class => 'btn btn-default' %>

<% end %>

app/views/organisations/edit.html.erb
<%- model_class = Organisation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organisations/index.html.erb
<%- model_class = Organisation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <th><%= model_class.human_attribute_name(:dataset) %></th>
      <th><%= model_class.human_attribute_name(:lat) %></th>
      <th><%= model_class.human_attribute_name(:long) %></th>
      <th><%= model_class.human_attribute_name(:suburb_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= link_to organisation.id, organisation_path(organisation) %></td>
        <td><%= organisation.name %></td>
        <td><%= organisation.website %></td>
        <td><%= organisation.dataset %></td>
        <td><%= organisation.lat %></td>
        <td><%= organisation.long %></td>
        <td><%= organisation.suburb.name unless organisation.suburb.nil?%></td>
        <td><%=l organisation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_organisation_path(organisation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      organisation_path(organisation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_organisation_path,
            :class => 'btn btn-primary' %>

<%= paginate @organisations %>

app/views/organisations/new.html.erb
<%- model_class = Organisation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organisations/show.html.erb
<%- model_class = Organisation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @organisation.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @organisation.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @organisation.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dataset) %>:</strong></dt>
  <dd><%= @organisation.dataset %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lat) %>:</strong></dt>
  <dd><%= @organisation.lat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:long) %>:</strong></dt>
  <dd><%= @organisation.long %></dd>
  <dt><strong><%= model_class.human_attribute_name(:suburb_id) %>:</strong></dt>
  <dd><%= @organisation.suburb_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              organisations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organisation_path(@organisation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organisation_path(@organisation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-md-9">
    <div id="map" style="width: 100%; height: 830px;">
    </div>
  </div>
  <div class="col-md-3">
    <%= form_tag "/", method: :get, class: "form-horizontal"  do %>
      <div class="control-group">
        <%= label_tag "Datasets (shift select for multiple)", nil, class: "control-label" %>
        <%= select_tag "datasets", options_for_select(@datasets), multiple: true, class: "form-control"  %>
      </div>

      <div class="control-group">
        <%= label_tag "Options" %>
        <%= select_tag("group_by", options_for_select(["lat/long", "suburbs"]), class: "form-control") if true == false %>
      </div>
      <div class="control-group">
        <%= label_tag "Only ABN" %>
        <%= check_box_tag "abn" %>
      </div>

      <%= submit_tag "Submit", class: "btn btn-primary" %>
    <% end %>

    <h3> Top Suburbs </h3>
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <td> Suburb </td>
          <td> Organisations </td>
        </tr>
      </thead>
      <tbody>
        <% @org_suburb_count.each do |suburb, count| %>
          <tr>
            <td> <a id="suburb_<%= suburb.gsub(" ", "_") %>" href="#"><%= suburb %></a><td>
            <td> <%= count %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  handler = Gmaps.build('Google', { markers: { clusterer: { maxZoom: 16 } } } );
  handler.buildMap({ provider : {}, internal: {id: 'map'}}, function() {
    markers = handler.addMarkers(<%=raw @org_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(4);
  });

  getLatLng = function(id) {
    $.ajax({
      type: "GET", 
      url: "/latlong?suburb={0}".replace("{0}", id),
      dataType: "json",
      success: function(data) {
        handler.getMap().setCenter(new google.maps.LatLng(data.lat, data.long));
        handler.getMap().setZoom(10);
      },
      error : function(XMLHttpRequest, textStatus, errorThrown) {
        alert(textStatus);
        alert(XMLHttpRequest.responseText);
      }
    });
  }

  $(document).ready(function() {
    $("[id^=suburb_]").click(function() {
      getLatLng(this.id);
    });
  });

</script>

app/views/pages/sacommunity.html.erb
<div class="row">
  <div class="col-md-9">
    <div id="map" style='width: 100%; height: 600px;'>
    </div>
  </div>
  <div class="col-md-3">
    <h3> Top Suburbs </h3>
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <td> Suburb </td>
          <td> Count </td>
        </tr>
      </thead>
      <tbody>
        <% @org_suburb_count.each do |suburb, count| %>
          <tr>
            <td> <%= suburb %> <td>
            <td> <%= count %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider : {}, internal: {id: 'map'}}, function() {
    markers = handler.addMarkers(<%=raw @org_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(4);
  });

</script>

app/views/pages/suburbmap.html.erb
<div class="row">
  <div class="col-md-9">
    <div id="map" style="width: 100%; height: 700px;">
    </div>
  </div>
  <div class="col-md-3">
    <h3> Top Suburbs </h3>
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <td> Suburb </td>
          <td> Organisations </td>
        </tr>
      </thead>
      <tbody>
        <% @org_suburb_count.each do |suburb, count| %>
          <tr>
            <td> <a class="haha" href="#"><%= suburb %></a><td>
            <td> <%= count %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider : {}, internal: {id: 'map'}}, function() {
    markers = handler.addMarkers(<%=raw @suburb_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(4);
  });

  $(document).ready(function() {
    $('.haha').click(function() {
      return false;
    });
  });

</script>

app/views/suburbs/_form.html.erb
<%= form_for @suburb, :html => { :class => "form-horizontal suburb" } do |f| %>

    <% if @suburb.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@suburb.errors.count, "error") %> prohibited this suburb from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @suburb.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@suburb[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :postcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postcode, :class => 'form-control' %>
    </div>
    <%= error_span(@suburb[:postcode]) %>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%= error_span(@suburb[:state]) %>
  </div>
  <div class="control-group">
    <%= f.label :lat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>
    <%= error_span(@suburb[:lat]) %>
  </div>
  <div class="control-group">
    <%= f.label :long, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :long, :class => 'form-control' %>
    </div>
    <%= error_span(@suburb[:long]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            suburbs_path, :class => 'btn btn-default' %>

<% end %>

app/views/suburbs/edit.html.erb
<%- model_class = Suburb -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suburbs/index.html.erb
<%- model_class = Suburb -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:lat) %></th>
      <th><%= model_class.human_attribute_name(:long) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @suburbs.each do |suburb| %>
      <tr>
        <td><%= link_to suburb.id, suburb_path(suburb) %></td>
        <td><%= suburb.name %></td>
        <td><%= suburb.postcode %></td>
        <td><%= suburb.state %></td>
        <td><%= suburb.lat %></td>
        <td><%= suburb.long %></td>
        <td><%=l suburb.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_suburb_path(suburb), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      suburb_path(suburb),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_suburb_path,
            :class => 'btn btn-primary' %>

<%= paginate @suburbs %>

app/views/suburbs/latlong.json.erb
{
  "lat": <%= @suburb.lat %>,
  "long": <%= @suburb.long %>
}

app/views/suburbs/new.html.erb
<%- model_class = Suburb -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suburbs/show.html.erb
<%- model_class = Suburb -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @suburb.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @suburb.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @suburb.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lat) %>:</strong></dt>
  <dd><%= @suburb.lat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:long) %>:</strong></dt>
  <dd><%= @suburb.long %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              suburbs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_suburb_path(@suburb), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              suburb_path(@suburb),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>